### PR TITLE
Support for angular 6 and rxjs 6

### PR DESCRIPTION
**Pull request by chrispruitt**
This is an update to make ng-alerts compatible with angular 6 and rxjs 6. Everything seems to be working well on my end.

### CODE REVIEW

**Comment by flauc** [comment]
This is awesome, thank you @chrispruitt  👍

**Comment by chrispruitt** [comment]
Any chance you will be publishing the new version today?

**Comment by flauc** [comment]
just published, thanks again 👍

**Comment by chrispruitt** [comment]
you're the man, thanks!

**Pull request merged**
